# Generated by Django 2.2.2 on 2019-07-08 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [
        ('clave_unica_auth', '0001_initial'),
        ('clave_unica_auth', '0002_loginclaveunica_completed'),
        ('clave_unica_auth', '0003_loginclaveunica_user'),
        ('clave_unica_auth', '0004_auto_20190707_1720'),
        ('clave_unica_auth', '0005_auto_20190707_1738'),
        ('clave_unica_auth', '0006_auto_20190707_1808'),
        ('clave_unica_auth', '0007_auto_20190707_2110'),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.UUIDField(default=uuid.uuid4)),
                ('login_date', models.DateTimeField(auto_now_add=True)),
                ('authorization_code', models.CharField(max_length=120)),
                ('access_token', models.CharField(max_length=120)),
                ('remote_addr', models.CharField(max_length=254, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Login',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(max_length=50)),
                ('run_num', models.IntegerField()),
                ('run_dv', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
